### ISSUE TITLE
[Bug] linter crashes when import invailed rule

### ISSUE THREAD

**Issue by asef18766** [JacobLinCool/suggestion-bot#3]
steps to reproduce:
1. !linter import [[{}, ""]]

expected result:
1. linter style crashes
2. linter substitution crashes
3. linter list crashes

**Comment by JacobLinCool** [comment]
Thank you, it seems an upstream issue and fixed in `suggestion-module` [`v1.0.0-alpha-10`](https://github.com/JacobLinCool/pure-cat-module-suggestion/tree/32ddfe939ca6eea532cc6f1ce29eaf7644a296ec).

I will update the dependency as soon as possible.
